-- Curated manager avatars: square slug-named images (`*-sq.png`) in public bucket `manager-avatars`.
-- Starter pack: `packs/starter-pack/` (see scripts/sync-starter-pack-avatars.ts).
-- Legacy paths: bucket root or `presets/` (migrated by sync script).
-- Catalog rows live in public.avatars (see supabase/avatar_packs.sql).
