-- Official salary cap tiers for Road to SummerSlam (and other salary_cap leagues).
-- Run after supabase/leagues_salary_cap.sql. Safe to re-run (overwrites salary_cap_cost for listed wrestlers).
-- Uses a CTE only (no temp tables) so Supabase SQL editor won't flag RLS on _salary_cap_seed.

with salary_cap_seed(name, cost) as (
  values
    -- $25
    ('Cody Rhodes', 25),
    ('Liv Morgan', 25),
    ('Rhea Ripley', 25),
    ('Roman Reigns', 25),
    -- $20
    ('CM Punk', 20),
    ('Gunther', 20),
    ('Jacob Fatu', 20),
    ('Jade Cargill', 20),
    ('Randy Orton', 20),
    -- $15
    ('Becky Lynch', 15),
    ('Bron Breakker', 15),
    ('Drew McIntyre', 15),
    ('Jey Uso', 15),
    ('Oba Femi', 15),
    ('Penta', 15),
    ('Seth Rollins', 15),
    ('Stephanie Vaquer', 15),
    ('Tiffany Stratton', 15),
    ('Trick Williams', 15),
    -- $10
    ('Austin Theory', 10),
    ('Brie Bella', 10),
    ('Damian Priest', 10),
    ('Dominik Mysterio', 10),
    ('Ethan Page', 10),
    ('Iyo Sky', 10),
    ('Jacy Jayne', 10),
    ('Je''Von Evans', 10),
    ('LA Knight', 10),
    ('Lash Legend', 10),
    ('Logan Paul', 10),
    ('Paige', 10),
    ('R-Truth', 10),
    ('Raquel Rodriguez', 10),
    ('Royce Keys', 10),
    ('Rusev', 10),
    ('Sami Zayn', 10),
    ('Sol Ruca', 10),
    -- $5
    ('AJ Lee', 5),
    ('Akira Tozawa', 5),
    ('Akira Tozowa', 5),
    ('Alexa Bliss', 5),
    ('Angel', 5),
    ('Angelo Dawkins', 5),
    ('Asuka', 5),
    ('Axiom', 5),
    ('B-Fab', 5),
    ('Bayley', 5),
    ('Berto', 5),
    ('Bianca Belair', 5),
    ('Blake Monroe', 5),
    ('Brad Baylor', 5),
    ('Bronson Reed', 5),
    ('Brutus Creed', 5),
    ('Bruto Creedo', 5),
    ('Candice LeRae', 5),
    ('Carmelo Hayes', 5),
    ('Channing Lorenzo', 5),
    ('Charlotte Flair', 5),
    ('Chelsea Green', 5),
    ('Cruz Del Torro', 5),
    ('Danhausen', 5),
    ('Dion Lennox', 5),
    ('Dragon Lee', 5),
    ('EK Prosper', 5),
    ('El Grande Americano', 5),
    ('Ludwig Kaiser', 5),
    ('Erik', 5),
    ('Fallon Henley', 5),
    ('Finn Balor', 5),
    ('Giulia', 5),
    ('Grayson Waller', 5),
    ('Hank Walker', 5),
    ('Ilja Dragunov', 5),
    ('Ivar', 5),
    ('Izzi Dame', 5),
    ('Jackson Drake', 5),
    ('Jaida Parker', 5),
    ('Jasper Troy', 5),
    ('JD McDonagh', 5),
    ('Jimmy Uso', 5),
    ('Joaquin Wilde', 5),
    ('Joe Hendry', 5),
    ('Johnny Gargano', 5),
    ('Jordynne Grace', 5),
    ('Julius Creed', 5),
    ('Julio Creedo', 5),
    ('Kali Armstrong', 5),
    ('Kam Hendrix', 5),
    ('Keanu Carver', 5),
    ('Kelani Jordan', 5),
    ('Kendal Grey', 5),
    ('Kevin Owens', 5),
    ('Kianna James', 5),
    ('Kit Wilson', 5),
    ('Lainey Reid', 5),
    ('Lexis King', 5),
    ('Lizzy Rain', 5),
    ('Lola Vice', 5),
    ('Mason Rook', 5),
    ('Matt Cardona', 5),
    ('Maxxine Dupri', 5),
    ('Michin', 5),
    ('Minihausen', 5),
    ('Montez Ford', 5),
    ('Myles Borne', 5),
    ('Naomi', 5),
    ('Naraku', 5),
    ('Nathan Frazer', 5),
    ('Nattie', 5),
    ('Nia Jax', 5),
    ('Nikki Bella', 5),
    ('Original El Grande Americano', 5),
    ('Chad Gable', 5),
    ('Osiris Griffin', 5),
    ('Otis', 5),
    ('Pat McAfee', 5),
    ('Rayo Americano', 5),
    ('Pete Dunne', 5),
    ('Piper Niven', 5),
    ('Rey Fenix', 5),
    ('Rey Mysterio', 5),
    ('Ricky Saints', 5),
    ('Ricky Smokes', 5),
    ('Roxanne Perez', 5),
    ('Santos Escobar', 5),
    ('Saquon Shugars', 5),
    ('Sean Legacy', 5),
    ('Sheamus', 5),
    ('Shiloh Hill', 5),
    ('Shinsuke Nakamura', 5),
    ('Solo Sikoa', 5),
    ('Talla Tonga', 5),
    ('Tama Tonga', 5),
    ('Tank Ledger', 5),
    ('Tatum Paxley', 5),
    ('Tavion Heights', 5),
    ('The Miz', 5),
    ('Thea Hail', 5),
    ('Tony D''Angelo', 5),
    ('Bravo Americano', 5),
    ('Tyler Bate', 5),
    ('Uriah Connors', 5),
    ('Wren Sinclair', 5),
    ('Zaria', 5)
),
seed_with_slug as (
  select
    name,
    cost,
    lower(
      trim(both '-' from
        regexp_replace(
          regexp_replace(lower(trim(name)), '[^a-z0-9]+', '-', 'g'),
          '-+',
          '-',
          'g'
        )
      )
    ) as slug
  from salary_cap_seed
)
update public.wrestlers w
set salary_cap_cost = s.cost
from seed_with_slug s
where lower(trim(w.name)) = lower(trim(s.name))
   or lower(trim(w.id)) = s.slug;

-- Apostrophe variants for Je'Von Evans.
update public.wrestlers
set salary_cap_cost = 10
where lower(trim(name)) in ('je''von evans', 'jevon evans', 'je’von evans')
   or lower(trim(id)) in ('je-von-evans', 'jevon-evans');
