import {
  AUTOPICK_REQUIRED_PRIORITY_COUNT,
  getAutopickRequiredPriorityCount,
} from "@/lib/draftPriorityRequirements";

/**
 * Pre-built priority lists (“Big Boards”) managers can pick instead of ranking manually.
 * Each `wrestlerIds` array must be at least {@link AUTOPICK_REQUIRED_PRIORITY_COUNT} long
 * (and {@link getAutopickRequiredPriorityCount}(true) for NXT/R2WG boards), in draft order
 * (at least 16 female — validated at draft time).
 */
export const BIG_BOARD_IDS = ["default", "dillster", "km_punk", "kayfabe_king"] as const;
export type BigBoardId = (typeof BIG_BOARD_IDS)[number];

export function getAvailableBigBoardIdsForLeague(params: {
  includeNxt?: boolean | null;
}): BigBoardId[] {
  const required = getAutopickRequiredPriorityCount(Boolean(params.includeNxt));
  // Only offer boards long enough for this league (NXT/R2WG needs the longer curated lists).
  return BIG_BOARD_IDS.filter((id) => DRAFT_BIG_BOARDS[id].wrestlerIds.length >= required);
}

/** Site default board for a league shape (Dillster for NXT/R2WG; Default otherwise). */
export function getDefaultBigBoardIdForLeague(params: {
  includeNxt?: boolean | null;
}): BigBoardId | null {
  const available = getAvailableBigBoardIdsForLeague(params);
  if (available.includes("default")) return "default";
  return available[0] ?? null;
}

export const DRAFT_BIG_BOARDS: Record<
  BigBoardId,
  { label: string; description: string; wrestlerIds: readonly string[] }
> = {
  default: {
    label: "Default Big Board",
    description:
      "Road to War Games — ranked by 2026 overall fantasy points (NXT included). Updated 7/27/26.",
    wrestlerIds: [
      "cody-rhodes",
      "roman-reigns",
      "rhea-ripley",
      "penta",
      "trick-williams",
      "liv-morgan",
      "cm-punk",
      "oba-femi",
      "sami-zayn",
      "tiffany-stratton",
      "iyo-sky",
      "randy-orton",
      "logan-paul",
      "damian-priest",
      "brie-bella",
      "jade-cargill",
      "austin-theory",
      "jevon-evans",
      "carmelo-hayes",
      "gunther",
      "paige",
      "jey-uso",
      "raquel-rodriguez",
      "becky-lynch",
      "charlotte-flair",
      "jacob-fatu",
      "lash-legend",
      "giulia",
      "la-knight",
      "dominik-mysterio",
      "tony-dangelo",
      "drew-mcintyre",
      "stephanie-vaquer",
      "finn-balor",
      "r-truth",
      "sol-ruca",
      "alexa-bliss",
      "jimmy-uso",
      "bron-breakker",
      "lola-vice",
      "seth-rollins",
      "solo-sikoa",
      "talla-tonga",
      "royce-keys",
      "bayley",
      "chad-gable",
      "lyra-valkyria",
      "nia-jax",
      "kiana-james",
      "tama-tonga",
      "tatum-paxley",
      "zaria",
      "myles-borne",
      "aj-lee",
      "dragon-lee",
      "kendal-grey",
      "rusev",
      "brad-baylor",
      "ricky-smokes",
      "rey-mysterio",
      "brock-lesnar",
      "danhausen",
      "michin",
      "chelsea-green",
      "jd-mcdonagh",
      "montez-ford",
      "roxanne-perez",
      "angelo-dawkins",
      "lainey-reid",
      "kelani-jordan",
      "asuka",
      "b-fab",
      "jordynne-grace",
      "ricky-saints",
      "shiloh-hill",
      "wren-sinclair",
      "ethan-page",
      "fallon-henley",
      "ludwig-kaiser",
      "izzi-dame",
      "matt-cardona",
      "rey-fenix",
      "keanu-carver",
      "bronson-reed",
      "jacy-jayne",
      "dion-lennox",
      "lexis-king",
      "ilja-dragunov",
      "jackson-drake",
      "joe-hendry",
      "ek-prosper",
      "otis",
      "axiom",
      "natalya",
      "sean-legacy",
      "the-miz",
      "jaida-parker",
      "saquon-shugars",
      "johnny-gargano",
      "nikki-bella",
    ],
  },
  dillster: {
    label: "Dillster's Big Board",
    description: "Road to War Games — curated by Dillster (top 100, NXT included). Updated 7/27/26.",
    wrestlerIds: [
      "cody-rhodes",
      "cm-punk",
      "roman-reigns",
      "oba-femi",
      "seth-rollins",
      "trick-williams",
      "liv-morgan",
      "penta",
      "iyo-sky",
      "tiffany-stratton",
      "sami-zayn",
      "jade-cargill",
      "gunther",
      "charlotte-flair",
      "bron-breakker",
      "stephanie-vaquer",
      "sol-ruca",
      "jacob-fatu",
      "lyra-valkyria",
      "chad-gable",
      "raquel-rodriguez",
      "paige",
      "la-knight",
      "jey-uso",
      "damian-priest",
      "jevon-evans",
      "austin-theory",
      "dominik-mysterio",
      "randy-orton",
      "rhea-ripley",
      "lainey-reid",
      "fallon-henley",
      "tony-dangelo",
      "zaria",
      "kendal-grey",
      "finn-balor",
      "carmelo-hayes",
      "montez-ford",
      "chelsea-green",
      "alexa-bliss",
      "bronson-reed",
      "jimmy-uso",
      "angelo-dawkins",
      "solo-sikoa",
      "lash-legend",
      "royce-keys",
      "michin",
      "r-truth",
      "lola-vice",
      "talla-tonga",
      "danhausen",
      "joe-hendry",
      "b-fab",
      "ricky-saints",
      "bayley",
      "nia-jax",
      "brie-bella",
      "becky-lynch",
      "roxanne-perez",
      "giulia",
      "rey-fenix",
      "ethan-page",
      "dragon-lee",
      "rey-mysterio",
      "rusev",
      "tama-tonga",
      "myles-borne",
      "jacy-jayne",
      "kiana-james",
      "dion-lennox",
      "jd-mcdonagh",
      "brad-baylor",
      "ricky-smokes",
      "kelani-jordan",
      "tatum-paxley",
      "wren-sinclair",
      "baron-corbin",
      "brock-lesnar",
      "naraku",
      "sean-legacy",
      "dorian-van-dux",
      "saquon-shugars",
      "shiloh-hill",
      "aj-lee",
      "keanu-carver",
      "lexis-king",
      "arianna-grace",
      "izzi-dame",
      "axiom",
      "jaida-parker",
      "tavion-heights",
      "matt-cardona",
      "lizzy-rain",
      "niko-vance",
      "tristan-angels",
      "ek-prosper",
      "nick-aldis",
      "el-grande-americano",
      "ivar",
      "erik",
    ],
  },
  km_punk: {
    label: "KM Punk's Big Board",
    description: "Road to War Games — curated by KM Punk (top 100, NXT included). Updated 7/27/26.",
    wrestlerIds: [
      "cody-rhodes",
      "cm-punk",
      "roman-reigns",
      "iyo-sky",
      "oba-femi",
      "trick-williams",
      "tiffany-stratton",
      "seth-rollins",
      "charlotte-flair",
      "liv-morgan",
      "chad-gable",
      "sol-ruca",
      "jade-cargill",
      "rhea-ripley",
      "gunther",
      "sami-zayn",
      "jey-uso",
      "stephanie-vaquer",
      "jacob-fatu",
      "paige",
      "finn-balor",
      "la-knight",
      "bron-breakker",
      "dominik-mysterio",
      "solo-sikoa",
      "austin-theory",
      "fallon-henley",
      "lainey-reid",
      "damian-priest",
      "carmelo-hayes",
      "jevon-evans",
      "royce-keys",
      "lash-legend",
      "raquel-rodriguez",
      "drew-mcintyre",
      "r-truth",
      "alexa-bliss",
      "jimmy-uso",
      "giulia",
      "nia-jax",
      "ethan-page",
      "rusev",
      "brie-bella",
      "nikki-bella",
      "danhausen",
      "chelsea-green",
      "baron-corbin",
      "randy-orton",
      "roxanne-perez",
      "kiana-james",
      "dragon-lee",
      "becky-lynch",
      "jd-mcdonagh",
      "tama-tonga",
      "joe-hendry",
      "jacy-jayne",
      "talla-tonga",
      "logan-paul",
      "lyra-valkyria",
      "michin",
      "blake-monroe",
      "tony-dangelo",
      "kendal-grey",
      "zaria",
      "b-fab",
      "myles-borne",
      "ricky-saints",
      "mike-santana",
      "bronson-reed",
      "rey-fenix",
      "rey-mysterio",
      "montez-ford",
      "angelo-dawkins",
      "tatum-paxley",
      "lola-vice",
      "kit-wilson",
      "the-miz",
      "brad-baylor",
      "ricky-smokes",
      "kelani-jordan",
      "wren-sinclair",
      "izzi-dame",
      "shiloh-hill",
      "matt-cardona",
      "jaida-parker",
      "natalya",
      "lexis-king",
      "naraku",
      "otis",
      "keanu-carver",
      "axiom",
      "aj-lee",
      "dion-lennox",
      "jackson-drake",
      "sean-legacy",
      "kali-armstrong",
      "tavion-heights",
      "lizzy-rain",
      "ilja-dragunov",
      "ek-prosper",
    ],
  },
  kayfabe_king: {
    label: "Kayfabe King's Big Board",
    description: "Road to War Games — curated by Kayfabe King (top 100, NXT included). Updated 7/27/26.",
    wrestlerIds: [
      "cody-rhodes",
      "cm-punk",
      "seth-rollins",
      "roman-reigns",
      "trick-williams",
      "penta",
      "liv-morgan",
      "oba-femi",
      "rhea-ripley",
      "gunther",
      "iyo-sky",
      "sami-zayn",
      "tiffany-stratton",
      "charlotte-flair",
      "jade-cargill",
      "damian-priest",
      "stephanie-vaquer",
      "brie-bella",
      "austin-theory",
      "jevon-evans",
      "carmelo-hayes",
      "paige",
      "jey-uso",
      "raquel-rodriguez",
      "becky-lynch",
      "jacob-fatu",
      "lash-legend",
      "giulia",
      "la-knight",
      "dominik-mysterio",
      "tony-dangelo",
      "drew-mcintyre",
      "finn-balor",
      "r-truth",
      "sol-ruca",
      "chad-gable",
      "jimmy-uso",
      "bron-breakker",
      "lola-vice",
      "solo-sikoa",
      "randy-orton",
      "talla-tonga",
      "royce-keys",
      "baron-corbin",
      "lyra-valkyria",
      "nia-jax",
      "kiana-james",
      "tama-tonga",
      "logan-paul",
      "kevin-owens",
      "tatum-paxley",
      "zaria",
      "myles-borne",
      "dragon-lee",
      "kendal-grey",
      "rusev",
      "brad-baylor",
      "ricky-smokes",
      "rey-mysterio",
      "danhausen",
      "michin",
      "chelsea-green",
      "bronson-reed",
      "jd-mcdonagh",
      "montez-ford",
      "roxanne-perez",
      "angelo-dawkins",
      "lainey-reid",
      "kelani-jordan",
      "nikki-bella",
      "alexa-bliss",
      "b-fab",
      "blake-monroe",
      "ricky-saints",
      "shiloh-hill",
      "wren-sinclair",
      "el-grande-americano",
      "ethan-page",
      "fallon-henley",
      "izzi-dame",
      "matt-cardona",
      "rey-fenix",
      "keanu-carver",
      "jacy-jayne",
      "dion-lennox",
      "lizzy-rain",
      "lexis-king",
      "mike-santana",
      "ilja-dragunov",
      "jackson-drake",
      "joe-hendry",
      "naraku",
      "ek-prosper",
      "otis",
      "axiom",
      "natalya",
      "sean-legacy",
      "the-miz",
      "jaida-parker",
      "saquon-shugars",
    ],
  },
};

export function isBigBoardId(value: string | null | undefined): value is BigBoardId {
  return value != null && (BIG_BOARD_IDS as readonly string[]).includes(value);
}

/** Returns a mutable copy of the board’s IDs, or null if unknown / not configured. */
export function getBigBoardPriorityList(boardId: string | null | undefined): string[] | null {
  if (!isBigBoardId(boardId)) return null;
  const ids = DRAFT_BIG_BOARDS[boardId].wrestlerIds;
  if (!ids.length || ids.length < AUTOPICK_REQUIRED_PRIORITY_COUNT) return null;
  return [...ids];
}

export function bigBoardLabel(boardId: BigBoardId): string {
  return DRAFT_BIG_BOARDS[boardId].label;
}

/**
 * True when a manager's saved autopick prefs are ready for draft:
 * a provided Big Board available for this league, or a custom list long enough
 * for the league's NXT/non-NXT requirement.
 */
export function hasAdequateAutopickDraftPreferences(params: {
  includeNxt?: boolean | null;
  priorityList?: string[] | null;
  priorityListSource?: string | null;
}): boolean {
  const includeNxt = Boolean(params.includeNxt);
  const required = getAutopickRequiredPriorityCount(includeNxt);
  const available = getAvailableBigBoardIdsForLeague({ includeNxt });
  const src = params.priorityListSource?.trim() || null;
  if (src && src !== "custom" && isBigBoardId(src) && available.includes(src)) {
    const board = getBigBoardPriorityList(src);
    return Boolean(board && board.length >= required);
  }
  return (params.priorityList?.length ?? 0) >= required;
}

/**
 * If the saved priority list exactly matches a Big Board (order + ids, case-insensitive), return that board id.
 * Used when `priorityListSource` was not stored (legacy rows).
 */
export function inferListSourceFromSavedList(priorityList: string[]): BigBoardId | null {
  if (priorityList.length < AUTOPICK_REQUIRED_PRIORITY_COUNT) return null;
  const norm = (s: string) => String(s).trim().toLowerCase();
  for (const boardId of BIG_BOARD_IDS) {
    const boardList = DRAFT_BIG_BOARDS[boardId].wrestlerIds;
    if (boardList.length !== priorityList.length) continue;
    let match = true;
    for (let i = 0; i < priorityList.length; i++) {
      if (norm(boardList[i]!) !== norm(priorityList[i]!)) {
        match = false;
        break;
      }
    }
    if (match) return boardId;
  }
  return null;
}
